services:
  streamlit_app:
    container_name: streamlit-app
    build:
      context: .
    environment:
      - STREAMLIT_APP_HOST=0.0.0.0
      - POSTGRESQL_DB_HOST=postgresql_db
    env_file:
      - ./.env
    restart: always
    ports:
      - 8501:8501
    depends_on:
      - postgresql_db
    volumes:
      - streamlit_app_data:/var/lib/streamlit_app/data

  postgresql_db:
    container_name: postgresql-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=invoices_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_db_data:/var/lib/postgresql_db/data

volumes:
  streamlit_app_data:
  postgresql_db_data:
